### ISSUE TITLE
Mock Community Question

### ISSUE THREAD

**Issue by MycoMap** [nextgenusfs/ufits#12]
ufits filter command

one of the lines contained:
[09:47:33 AM]: Mock members not found: mock_10, mock_7, mock_8, mock_9, mock_1, mock_11, mock_12, mock_2, mock_3, mock_4, mock_5, mock_6

Wondering if you could comment on that. Also continuing a few lines down, there was an error:

[09:47:33 AM]: Sorting OTU table naturally
[09:47:33 AM]: Removing OTUs according to --min_reads_otu: (OTUs with less than 2 reads from all samples)
[09:47:33 AM]: Normalizing OTU table to number of reads per sample
/home/srussell/ufits/bin/ufits-filter.py:227: RuntimeWarning: invalid value encountered in double_scalars
  bleed1max = bleed1 / float(total)

**Comment by nextgenusfs** [comment]
What was the command that you issued here?

**Comment by MycoMap** [comment]
ufits filter -i out.otu_table.txt -f out.cluster.otus.fa -b MADMOCK

Mock community files: MADMOCK_S144_L001_R1_001.fastq; MADMOCK_S144_L001_R2_001.fastq

**Comment by nextgenusfs** [comment]
You need to specify a multi fasta file using the --mc flag if you are not using the default mock community

**Comment by nextgenusfs** [comment]
Is this a mock community that we sent you?

**Comment by MycoMap** [comment]
It is not. Can you send it to me?

**Comment by nextgenusfs** [comment]
Referring to the error - I think the most recent release (v0.6.0) should have this fixed.

**Comment by nextgenusfs** [comment]
`--mc` is now required for filtering. https://github.com/nextgenusfs/ufits/releases/tag/0.7.0
