### ISSUE TITLE
usearch9 multithread fastq_filter is crashing

### ISSUE THREAD

**Issue by hyphaltip** [nextgenusfs/ufits#13]
Per this problem with usearch 9 http://www.drive5.com/usearch/manual/malloc_bug_v9.html

I edited ufits code to add the '-threads' cpu and requested 1 cpu and it would succeed - probably should just force this step to be single threaded all the time but not force the whole pipeline to be cpu=1 

```
51c51,54
<     cmd = [usearch, '-fastq_filter', R1, '-fastq_trunclen', str(read_length), '-fastqout', pretrim_R1]
---
>     threads = 1
>     cmd = [usearch, '-fastq_filter', R1, '-fastq_trunclen', str(read_length), '-fastqout', pretrim_R1, '-threads', str(threads)]
53c56
<     cmd = [usearch, '-fastq_filter', R2, '-fastq_trunclen', str(read_length), '-fastqout', pretrim_R2]
---
>     cmd = [usearch, '-fastq_filter', R2, '-fastq_trunclen', str(read_length), '-fastqout', pretrim_R2, '-threads', str(threads)]
```

**Comment by nextgenusfs** [comment]
Ok, thanks this must be a linux only problem?  Do you see the problem with v9.1.13?  We can also use VSEARCH for this to avoid this problem, is it only in the `-fastq_filter` command or is it all commands?  This step is probably paranoia on my part, but just trying to trim off the index 'A' linker if reads are 251 instead of 250 or 301 instead of 300.

**Comment by hyphaltip** [comment]
So it only happens for the fastq_filter step and it only happens on Linux - I saw it on 9.0 and 9.1.13 - so I don't think that usearch has fixed.

I agree using vsearch for as many steps as possible anyways for these steps or others. I think usearch is faster for some of the other overlap steps.

**Comment by nextgenusfs** [comment]
switched to VSEARCH for this https://github.com/nextgenusfs/ufits/releases/tag/0.7.0
