### ISSUE TITLE
ufits taxonomy: make OTU table optional

### ISSUE THREAD

**Issue by vmikk** [nextgenusfs/ufits#7]
Hello Jon! 
Thanks a lot for UFITS, I find it very useful and user-friendly!
I would like to propose to make the input OTU table (`-i` or `--otu_table` flags) optional in `ufits taxonomy`. The hybrid approach for taxonomic assignment is very handy by itself. So it would be nice if the users will be able to perform taxonomic annotation for any FASTA file just with a single command, e.g.:
```
ufits taxonomy -f tst.fasta -d ITS2 --method hybrid
```
Now it almost works, but will not produce the “hybrid” of usearch (global alignment) and UTAX results without OTU table.

With best regards,
Vladimir

**Comment by nextgenusfs** [comment]
Hi Vladimir,

Sure, this is an easy update - I will push the update later today.  Glad you find it useful.

Jon

**Comment by nextgenusfs** [comment]
fixed https://github.com/nextgenusfs/ufits/commit/c7df840be42ed3823f88906f8c8d9b265ee12a44

new release here: https://github.com/nextgenusfs/ufits/releases/tag/0.4.9

**Comment by vmikk** [comment]
That's perfect, thank you!
